export const PATH_SIGNUP = "/sign-up";
export const PATH_SIGNIN= "/sign-in";
export const PATH_DASHBOARD = "/dashboard";
export const PATH_RESET_PASSWORD = "/reset-password";
export const PATH_COURSES = "/courses";
export const PATH_ADD_NEW_COURSE = PATH_COURSES + "/addNew-course";
export const PATH_USER_MANAGEMENT = "/user-management";
export const PATH_COURSE_DETAIL = "/course-detail/:courseId";
export const PATH_EDIT_COURSE = "/edit-course/:courseId";