export const tableData = [
  {
    course: "Compensation and Benefits Policies",
    scoreAchieved: "-",
    timeTaken: "2hr 25min",
    noOfAttempts: "-",
    assignedDate: "Jan 12, 2024",
    completedDate: "Jan 12, 2024",
    taskStatus: "Completed",
    subCourses: [
      {
        course: "Salary Structure and Increments",
        scoreAchieved: "92.21%",
        timeTaken: "25 min",
        noOfAttempts: "04",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "Health and Wellness Benefits",
        scoreAchieved: "89.73%",
        timeTaken: "1hr 15min",
        noOfAttempts: "02",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "Retirement and Savings Plans",
        scoreAchieved: "93.25%",
        timeTaken: "45 min",
        noOfAttempts: "04",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
    ],
  },
  {
    course: "Code of Conduct",
    scoreAchieved: "-",
    timeTaken: "-",
    noOfAttempts: "-",
    assignedDate: "-",
    completedDate: "Feb 07, 2024",
    taskStatus: "Completed",
    subCourses: [
      {
        course: "Workplace Ethics",
        scoreAchieved: "85.50%",
        timeTaken: "30 min",
        noOfAttempts: "02",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "Professional Conduct",
        scoreAchieved: "88.20%",
        timeTaken: "45 min",
        noOfAttempts: "03",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
    ],
  },
  {
    course: "Administrative Details",
    scoreAchieved: "-",
    timeTaken: "-",
    noOfAttempts: "-",
    assignedDate: "-",
    completedDate: "Feb 17, 2024",
    taskStatus: "Completed",
    subCourses: [
      {
        course: "Company Policies",
        scoreAchieved: "90.10%",
        timeTaken: "40 min",
        noOfAttempts: "02",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "HR Procedures",
        scoreAchieved: "87.60%",
        timeTaken: "50 min",
        noOfAttempts: "01",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
    ],
  },
  {
    course: "Job Role and Responsibilities",
    scoreAchieved: "-",
    timeTaken: "-",
    noOfAttempts: "-",
    assignedDate: "-",
    completedDate: "Mar 14, 2024",
    taskStatus: "Completed",
    subCourses: [
      {
        course: "Key Responsibilities",
        scoreAchieved: "91.30%",
        timeTaken: "35 min",
        noOfAttempts: "02",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "Performance Expectations",
        scoreAchieved: "86.50%",
        timeTaken: "40 min",
        noOfAttempts: "03",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
    ],
  },
  {
    course: "Employee Benefits and Compensation",
    scoreAchieved: "-",
    timeTaken: "-",
    noOfAttempts: "-",
    assignedDate: "-",
    completedDate: "Apr 04, 2024",
    taskStatus: "Completed",
    subCourses: [
      {
        course: "Medical Insurance",
        scoreAchieved: "94.00%",
        timeTaken: "30 min",
        noOfAttempts: "01",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
      {
        course: "Retirement Plans",
        scoreAchieved: "92.75%",
        timeTaken: "45 min",
        noOfAttempts: "02",
        assignedDate: "-",
        completedDate: "-",
        taskStatus: "-",
      },
    ],
  },
];
