import React from "react";
import { Text } from "@react-pdf/renderer";
import styles from "./PDFStyles";

const PDFFooter = () => (
  <Text style={styles.footer}>
    Generated by Training Management System | {new Date().toLocaleString()}
  </Text>
);

export default PDFFooter;
